config/routes.rb
Rails.application.routes.draw do
  root "series#index"

  resources :series do
    resources :game
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :series

  validates :score, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 300
  }
end

app/models/series.rb
class Series < ActiveRecord::Base
  has_many :games
  accepts_nested_attributes_for :games

  validates :date, presence: true

  attr_accessor :running_average

  def total
    total = 0;
    self.games.each do |game|
      total += game.score
    end
    total
  end

  def average
    self.total / self.games.size
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @all_stats = SeriesStatistics.from_series_list(Series.includes(:games))
  end

  def show
    @series = Series.find(params[:id])
  end

  def new
    @series = Series.new
    3.times { @series.games.build }
  end

  def create
    @series = Series.new(series_params)

    if @series.save
      redirect_to series_index_path
    else
      render "new"
    end
  end

  private
    def series_params
      params.require(:series).permit(:date, games_attributes: [:score])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bowling</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/series/_form.html.erb
<%= form_for @series do |f| %>

  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@series.errors.count, "error") %> prohibited
        this series from being saved:
      </h2>
      <ul>
        <% @series.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div>
      <%= f.label :date %>
      <%= f.date_field :date %>
    </div>

    <% @series.games.each.with_index do |game, index| %>
      <%= f.fields_for :games, game do |game_field| %>
        <div>
          <%= game_field.label :score, "Game #{index + 1}" %>
          <%= game_field.text_field :score %>
        </div>
      <% end %>
    <% end %>
  </fieldset>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/series/index.html.erb
<h1>All Series</h1>

<%= link_to "Add a new series", new_series_path %>

<table class="series-listing">
  <tr>
    <th>Date</th>
    <th>Game 1</th>
    <th>Game 2</th>
    <th>Game 3</th>
    <th>Series Total</th>
    <th>Series Average</th>
    <th>Running Average</th>
  </tr>
  <% @all_stats.each do |stats| %>
    <tr>
      <td><%= stats.series.date %></td>
      <% stats.series.games.each.with_index do |game, index| %>
        <td><%= game.score %></td>
      <% end %>
      <td><%= stats.series.total %></td>
      <td><%= stats.series.average %></td>
      <td><%= stats.running_average %></td>
    </tr>
  <% end %>
</table>

app/views/series/new.html.erb
<h1>Add a New Series</h1>

<%= render 'form' %>

<%= link_to 'Go to listing', series_index_path %>